import { ElementRef, EventEmitter, Renderer } from 'angular2/core';
import { ControlValueAccessor } from 'angular2/src/common/forms/directives/control_value_accessor';
export declare class Md2Switch implements ControlValueAccessor {
    private _renderer;
    private _elementRef;
    ariaLabel: string;
    id: string;
    align: string;
    disabled: boolean;
    tabindex: number;
    change: EventEmitter<boolean>;
    onTouched: () => any;
    private _currentAnimationClass;
    private _currentCheckState;
    private _checked;
    private _indeterminate;
    private _changeSubscription;
    constructor(_renderer: Renderer, _elementRef: ElementRef);
    checked: boolean;
    indeterminate: boolean;
    labelId: string;
    getAriaChecked(): string;
    toggle(): void;
    onInteractionEvent(event: Event): void;
    writeValue(value: any): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    private _transitionCheckState(newState);
    private _getAnimationClassForCheckStateTransition(oldState, newState);
}
